import turtle
from turtle import *
from random import randint
screen=turtle.Screen()
left(140)
penup()
forward(225)
left(130)
#making racetrack and assigning initial positions to turtles
for step in range(16):
    pendown()
    forward(250)
    penup()
    backward(250)
    left(90)
    forward(20)
    right(90)
    speed(0)
solo=Turtle()
solo.color('red')
solo.shape('turtle')
solo.penup()
solo.goto(-200,120)
bye=Turtle()
bye.color('blue')
bye.shape('turtle')
bye.penup()
bye.goto(-200,80)
got=Turtle()
got.color('yellow')
got.shape('turtle')
got.penup()
got.goto(-200,40)
bat=Turtle()
bat.color('violet')
bat.shape('turtle')
bat.penup()
bat.goto(-200,0)
cool=Turtle()
cool.color('green')
cool.shape('turtle')
cool.penup()
cool.goto(-200,-40)
that=Turtle()
that.color('orange')
that.shape('turtle')
that.penup()
that.goto(-200,-80)
#using random variable and creating a loop
for move in range(115):
    solo.pendown()
    solo.forward(randint(1,5))
    solo.speed(randint(1,4))
    cool.pendown()
    cool.forward(randint(1,5))
    cool.speed(randint(1,4))
    got.pendown()
    got.forward(randint(1,5))
    got.speed(randint(1,4))
    that.pendown()
    that.forward(randint(1,5))
    that.speed(randint(1,4))
    bat.pendown()
    bat.forward(randint(1,5))
    bat.speed(randint(1,4))
    bye.pendown()
    bye.forward(randint(1,5))
    bye.speed(randint(1,4))

solo.left(180)
cool.left(180)
got.left(180)
bat.left(180)
bye.left(180)
that.left(180)

for back in range(110):
    solo.pendown()
    solo.forward(randint(1,5))
    solo.speed(randint(1,4))
    cool.pendown()
    cool.forward(randint(1,5))
    cool.speed(randint(1,4))
    got.pendown()
    got.forward(randint(1,5))
    got.speed(randint(1,4))
    that.pendown()
    that.forward(randint(1,5))
    that.speed(randint(1,4))
    bat.pendown()
    bat.forward(randint(1,5))
    bat.speed(randint(1,4))
    bye.pendown()
    bye.forward(randint(1,5))
    bye.speed(randint(1,4))